version: '3.8'
name: fluentpos

services:
  gateway:
    container_name: "gateway"
    image: iammukeshm/fluentpos.gateway:latest
    ports:
      - 7002:7002
      - 5002:5002
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - ASPNETCORE_URLS=https://+:7002;http://+:5002
      - ASPNETCORE_HTTPS_PORT=7002
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cert.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    networks:
     - fluentpos
  identity:
    container_name: identity
    image: iammukeshm/fluentpos.identity:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    depends_on:
      postgres:
        condition: service_healthy
    networks:
     - fluentpos
  catalog:
    container_name: catalog
    image: iammukeshm/fluentpos.catalog:latest
    depends_on:
      - mongo
      - placement
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    networks:
     - fluentpos
  catalog-dapr:
    container_name: catalog-dapr
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "catalog",
     "-placement-host-address", "placement:6050",
     "-app-port", "80",
     "-components-path", "/dapr/components"]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      - catalog
    network_mode: "service:catalog"

  cart:
    container_name: cart
    image: iammukeshm/fluentpos.cart:latest
    depends_on:
      - placement
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    networks:
     - fluentpos
  cart-dapr:
    container_name: cart-dapr
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "cart",
     "-placement-host-address", "placement:6050",
     "-app-port", "80",
     "-components-path", "/dapr/components"]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      - cart
    network_mode: "service:cart"