apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rabbitmq
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: connectionString
    secretKeyRef:
      name: rmqConnectionString
      key: rmqConnectionString
  - name: durable
    value: false
  - name: deletedWhenUnused
    value: false
  - name: autoAck
    value: false
  - name: reconnectWait
    value: 0
  - name: concurrency
    value: parallel
auth:
  secretStore: secretstore
scopes:
- cart
- catalog
- identity
- gateway