name: fluentpos
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      build_gateway_image:
        type: boolean
        description: push gateway image
      build_identity_image:
        type: boolean
        description: push identity image
      build_catalog_image:
        type: boolean
        description: push catalog image
      build_cart_image:
        type: boolean
        description: push cart image        
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        working-directory: ./fluentpos/
        run: dotnet restore
      - name: Build
        working-directory: ./fluentpos/
        run: dotnet build --no-restore
      - name: Test
        working-directory: ./fluentpos/
        run: dotnet test --no-build --verbosity normal
  docker:
    name: Docker
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - if: github.event.inputs.build_gateway_image == 'true' || github.ref == 'refs/heads/main'
        name: Build Gateway Image
        working-directory: ./
        run: |
          dotnet publish fluentpos/gateways/Gateway/Gateway.csproj --os linux --arch x64 -c Release -p:PublishProfile=DefaultContainer -p:ContainerImageName=${{ secrets.DOCKER_USERNAME }}/fluentpos.gateway
          docker push ${{ secrets.DOCKER_USERNAME }}/fluentpos.gateway --all-tags

      - if: github.event.inputs.build_identity_image == 'true' || github.ref == 'refs/heads/main'
        name: Build Identity Server Image
        working-directory: ./
        run: |
          dotnet publish fluentpos/services/identity/Api/Api.csproj --os linux --arch x64 -c Release -p:PublishProfile=DefaultContainer -p:ContainerImageName=${{ secrets.DOCKER_USERNAME }}/fluentpos.identity
          docker push ${{ secrets.DOCKER_USERNAME }}/fluentpos.identity --all-tags

      - if: github.event.inputs.build_catalog_image == 'true' || github.ref == 'refs/heads/main'
        name: Build Catalog Service Image
        working-directory: ./
        run: |
          dotnet publish fluentpos/services/catalog/Api/Api.csproj --os linux --arch x64 -c Release -p:PublishProfile=DefaultContainer -p:ContainerImageName=${{ secrets.DOCKER_USERNAME }}/fluentpos.catalog
          docker push ${{ secrets.DOCKER_USERNAME }}/fluentpos.catalog --all-tags
      
      - if: github.event.inputs.build_cart_image == 'true' || github.ref == 'refs/heads/main'
        name: Build Cart Service Image
        working-directory: ./
        run: |
          dotnet publish fluentpos/services/cart/Api/Api.csproj --os linux --arch x64 -c Release -p:PublishProfile=DefaultContainer -p:ContainerImageName=${{ secrets.DOCKER_USERNAME }}/fluentpos.cart
          docker push ${{ secrets.DOCKER_USERNAME }}/fluentpos.cart --all-tags    